homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 59
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enables the MQTT broker
mqtt:

# Device tracking
device_tracker:
 - platform: mqtt_json
   consider_home: 180
   devices:
    amaury_oneplusx: zanzito/oneplusx/location

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    entities:
      - sensor.aeotec_zw100_multisensor_6_temperature
      - input_number.thermostat_tv_room
      - sensor.aeotec_zw100_multisensor_6_relative_humidity
      - sensor.aeotec_zw100_multisensor_6_luminance
      - light.qubino_dimmer_heater_tv_level
      - input_select.heating_mode_tv_room
      - sensor.yweather_temperature
      - sensor.yweather_humidity
      - sensor.yweather_condition
      - device_tracker.amaury_oneplusx

history_graph:
  graph_temp_tv_room:
    name: Températures Pièce TV
    entities:
      - input_number.thermostat_tv_room
      - sensor.aeotec_zw100_multisensor_6_temperature
      - sensor.yweather_temperature
    hours_to_show: 24
    refresh: 60
  graph_heater_mode:
    name: Mode chauffage
    entities:
      - input_select.heating_mode_tv_room
      - light.qubino_dimmer_heater_tv_level
    hours_to_show: 24
    refresh: 60
  graph_humidity_tv_room:
    name: Humidité Pièce TV
    entities:
      - sensor.aeotec_zw100_multisensor_6_relative_humidity
      - sensor.yweather_humidity
    hours_to_show: 24
    refresh: 60
  graph_luminance_tv_room:
    name: Luminosité Pièce TV
    entities:
      - sensor.aeotec_zw100_multisensor_6_luminance
    hours_to_show: 24
    refresh: 60
  graph_geofencing:
    name: Localisation
    entities:
      - device_tracker.amaury_oneplusx
# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:
zone: !include zones.yaml

# Track the sun
#sun:

# Weather prediction
sensor:
  - platform: yweather
    monitored_conditions:
      - humidity
      - temperature
      - wind_speed
      - weather

# Text to speech
tts:
  - platform: google

# Cloud
# cloud:

# Media players
#media_player:
#  - platform: plex
#    entity_namespace: 'plex'
#    include_non_clients: true
#    scan_interval: 5
#    show_all_controls: true
#    use_custom_entity_ids: true
#    use_episode_art: false

# Python scripts
python_script:

# Z-wave
zwave:
  usb_path: \\.\COM4

automation: !include_dir_merge_list automation
group: !include groups.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
script: !include scripts.yaml
