###########################################################
# TV ROOM
###########################################################

# Regulates the TV room temperature
- alias: Réguler température Pièce TV
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_temperature
    - platform: state
      entity_id: input_number.thermostat_tv_room
    - platform: state
      entity_id: input_boolean.activate_thermostat_tv_room
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.activate_thermostat_tv_room
        state: 'on'
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.heating_mode_tv_room
      option: >
        {% if states('sensor.aeotec_zw100_multisensor_6_temperature') | float - states('input_number.thermostat_tv_room') | float < 0 %}
          Confort
        {% else %}
          Eteind
        {% endif %}

# Set thermostat at 18 degrees when leaving home
- alias: Régler thermostat sur 18 degrés quand absent
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.activate_thermostat_tv_room
    state: 'on'
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.thermostat_tv_room
      value: 18

# Set thermostat at 20 degrees when getting home
- alias: Régler thermostat sur 20 degrés quand à la maison
  trigger:
    - platform: state
      entity_id: device_tracker.amaury_oneplusx
      to: 'home'
    - platform: state
      entity_id: device_tracker.iphone_de_maud
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.activate_thermostat_tv_room
    state: 'on'
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.thermostat_tv_room
      value: 20